### ISSUE TITLE
Add pylint for Python code

### ISSUE THREAD

**Issue by U8NWXD** [oppia/oppia-web-developer-docs#100]
We should enforce out-of-the-box pylint rules for all Python code files in the docs repository. Pylint should run as part of CI checks for all PRs and on all commits to develop. It should also be easy for developers to run the lint checks locally.

**Comment by SD-13** [comment]
Hey @U8NWXD, Can I take this one?

**Comment by U8NWXD** [comment]
@SD-13 I don't think this one is ready yet--we still need to decide what exactly we want the linter to require. If you have ideas about what practices we should enforce, I'd love to hear them!

**Comment by U8NWXD** [comment]
@SD-13 okay I decided we can use pylint out-of-the-box and assigned you. When do you plan to complete this issue?

**Comment by SD-13** [comment]
@U8NWXD probably, within the next two week

**Comment by SD-13** [comment]
@U8NWXD should we use pylint in the GitHub workflow or as a pre-commit linter? Since we are already using workflows in this repo and we don't require any installation for local setup yet, I am more towards using GitHub actions for this. What do you think?

**Comment by U8NWXD** [comment]
Yep, I agree with making this a GitHub workflow. CI checks are fast in this repo, so there's not much benefit to pre-push checks right now

**Comment by SD-13** [comment]
> It should also be easy for developers to run the lint checks locally.

Thinking about this line in the issue description, it will be like 2 steps
1. Install pylint( `pip install pylint` or `pip3 install pylint` ) (assuming python and pip are already installed)
2. Run pylint( `pylint **/*.py` )

So, do you think we need to document it or comment on it to help devs run it locally?

**Comment by U8NWXD** [comment]
I do think we should document both steps (how to install pylint and how to run it)--this can go in our wiki page for the wiki: https://github.com/oppia/oppia/wiki/Wiki. I agree that this is simple enough that we don't need additional infrastructure (e.g. Python scripts to run the lint checks like we have on oppia-web).
