### ISSUE TITLE
Make contribution pre-requisites clear

### ISSUE THREAD

**Issue by U8NWXD** [oppia/oppia-web-developer-docs#110]
In our documentation, we make some assumptions about what contributors know:

* We assume readers understand standard Unix path notation, including `~` as an abbreviation for the home directory.
* We assume developers know how to edit and create text files, e.g. `~/.direnvrc`.

These were raised in https://github.com/oppia/oppia/discussions/17329#discussioncomment-4950833.

We should make these per-requisites clear in our documentation, perhaps on the installation landing page

**Comment by vedant-z** [comment]
@U8NWXD I think this can be solved by completing following steps:

- Mention clearly the pre-requisite "Readers should know Unix path notations and related things clearly." in documentation with some basic examples like ```~``` abbreviation.
- Pre-requisite "Developers should know how to use Git and GitHub and basic things like how to raise a PR, creating and editing files."
