### ISSUE TITLE
Link not working in the Testing for Accessibility wiki page

### ISSUE THREAD

**Issue by Patel-Muhammad** [oppia/oppia-web-developer-docs#128]
This link " http://simplyaccessible.com/article/spangular-accessibility/ " which is there in the file: https://github.com/oppia/oppia-web-developer-docs/blob/develop/Testing-for-Accessibility.md at line 44 is no longer available. 

Screenshot:

<img width="960" alt="Screenshot 2023-03-06 200052" src="https://user-images.githubusercontent.com/96219910/223139358-6c4f7f0b-c4d9-4ad6-9cb9-77f6d7d4878e.png">

**Comment by Patel-Muhammad** [comment]
@seanlip PTAL. Thanks.

**Comment by seanlip** [comment]
Thanks for noting, @Patel-Muhammad. Here is a Wayback Machine version that you can replace it with (if you'd like): https://web.archive.org/web/20220206112133/http://simplyaccessible.com/article/spangular-accessibility/

**Comment by Patel-Muhammad** [comment]
@seanlip Sure I can replace it, but can we make it a good first issue so that new contributors can work on this?

**Comment by U8NWXD** [comment]
I'd say let's just go ahead and fix it. I think having a broken link is going to cause too much confusion, and we have lots of starter issues for new contributors. If you don't have time to fix it @Patel-Muhammad, that's fine--I'm just saying that you don't need to avoid fixing it to "save" it for new contributors

**Comment by Patel-Muhammad** [comment]
@U8NWXD got it, I can go ahead and fix this issue. Thanks.
