### ISSUE TITLE
Create documentation for the diagnostic test

### ISSUE THREAD

**Issue by Nik-09** [oppia/oppia-web-developer-docs#130]
Create documentation for the diagnostic test.

The documentation should contain the series of steps required to launch the diagnostic test functionality.

**Comment by seanlip** [comment]
@Nik-09 just a friendly ping on this issue please, thanks!

**Comment by SubhashThenua** [comment]
Hi @Nik-09 
Could you please provide me with an update when you plan to open the PR?
thanks!

**Comment by Nik-09** [comment]
Hi @SubhashThenua the doc is under review, I am estimating its completion by tomorrow.

**Comment by SubhashThenua** [comment]
thanks @Nik-09 for updating.

**Comment by seanlip** [comment]
Doc is [here](https://docs.google.com/document/d/1NzxJlu64bvdNw1CJ7aUR5XaZc-zfoXYgfYopEDVUcxk/edit#). This doesn't need to be done on the wiki so I'm closing this.
