### ISSUE TITLE
Broken link in 'Contributing code to Oppia'

### ISSUE THREAD

**Issue by howtofly-lab** [oppia/oppia-web-developer-docs#158]
Hi, in the' Contributing code to Oppia', the link for "Backend" does not direct to anything. Clicking on the link keeps me on the same page. Here's the link to 'Contributing code to Oppia': https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia

Here's a screenshot of the issue:
<img width="1030" alt="Screen Shot 2023-04-15 at 8 04 40 PM" src="https://user-images.githubusercontent.com/76920083/232259291-20bda3a8-e578-4b1d-9ed9-092416bdfe5e.png">

**Comment by gp201** [comment]
@howtofly-lab Nice catch! Thanks for reporting the issue.

**Comment by howtofly-lab** [comment]
Hi @gp201 I saw your pull request and saw that you deleted the "Backend" and "Frontend" labels. But I was thinking instead of deleting the labels, I can add a link to the Issues tab in the oppia repo that is filtered by "good first issue" and "backend" labels. Same for "Frontend".
