### ISSUE TITLE
[Oppia Web] Give guidance to developers for how to test emails

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-web-developer-docs#162]
It would probably be useful for developers to have a section explaining how to test functionality that involves emails, since these aren't set up to actually send an email anywhere except the prod environment (and we shouldn't use that for testing). In general, the basic idea is to make sure the relevant flags are turned on and look for the email text showing up in the server logs, but this flow needs to be verified/validated, probably using a step-by-step example.

(See https://github.com/oppia/oppia/issues/12062#issuecomment-1523300149 for an example of a developer looking for help with this.)

**Comment by vishisht-dubey** [comment]
Hiii @seanlip please assign this issue to me

**Comment by seanlip** [comment]
@vishisht-dubey  Per the guidance at https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue, please provide an explanation of what your PR will do (with names of files you're changing, what you plan to change in each file, etc.). If it looks good, we can assign you to this issue.

Please also follow the other instructions on that wiki page if you have not yet done so. Thanks!

**Comment by Ash-2k3** [comment]
I think, to verify that emails are working fine we can do two things, first is that unit tests should pass and second is we can use print statements, to checkout email body in server logs.

Edit: But I am not sure on how to give a step-by-step example. /cc @seanlip

**Comment by seanlip** [comment]
Take a look at core/platform/email/dev_mode_email_services.py. This is the file that handles emails in dev mode -- as you can see, it logs messages to the terminal using logging.info().

Now see if you can figure out how to do a real example that involves, e.g., sending the email that a user gets on signup. (Note that you might need to turn on various flags in the code like ENABLE_EMAILS etc. in order to do that, but working through this example should help you figure out what to change.)
