### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by ghost** [oppia/oppia-web-developer-docs#174]
### Issue Description:
There are some grammatical errors in [Wiki.md](https://github.com/oppia/oppia-web-developer-docs/blob/05d2aabec5f644d6094031800ffeb9c506f7096f/Wiki.md?plain=1) file.

### Issue and correction:
Here are a few minor corrections:

1)#L20:  In the sentence "This is our deployment repository where we put wiki source files to be viewed by the community," it would be more accurate to say "where we store" instead of "where we put."

2)#L31:  In the sentence "If the improvement you have in mind is big, you want feedback before you start working on it, or you don't have time to make the change yourself," it would be clearer to use "if" instead of "or" before "you don't have time to make the change yourself."

3)#L148:  In the sentence "The workflow uses the oppia/get-github-app-token action to retrieve an authentication token using the synchronizer bot's private key," it would be clearer to say "authentication token by utilizing" instead of "retrieving an authentication token using."

4)#L150:  In the sentence "The master:develop says to push the local master branch to the remote develop branch," it would be clearer to say "indicates pushing the local master branch" instead of "says to push the local master branch."

### Labels
"good first issue,impact: Low,Work: Low"

**Comment by RudrakshAtGithub** [comment]
@jahd2602 @brianrodri @kevinlee12 @kevjumba I would like to contribute to the above issue.

**Comment by ghost** [comment]
@seanlip ,I would like to contribute to above issue,please assign this issue to me.
Regards

**Comment by seanlip** [comment]
Thanks for the suggestion @RudrakshAtGithub. I don't think these are issues -- the new replacements are generally fine, but the existing text is also fine. So let's not do this.

If you'd like to take up an issue, I suggest following the instructions [here](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia) and trying your hand at an existing one. Thanks!

**Comment by ghost** [comment]
Oh gotcha! 
Thanks for the direction, will work on some other existing issues!
