### ISSUE TITLE
[BUG]: The play button does not open the video here : https://github.com/oppia/oppia/wiki/Make-a-pull-request

### ISSUE THREAD

**Issue by shrish-bhargav** [oppia/oppia-web-developer-docs#205]
### Describe the bug

In the page [Make a pull request](https://github.com/oppia/oppia/wiki/Make-a-pull-request) , there is a video description with the name demoOpenPR_480p.mov that does not actually play

### URL of the page where the issue is observed.

https://github.com/oppia/oppia/wiki/Make-a-pull-request

### Steps To Reproduce

Go to the [this page](https://github.com/oppia/oppia/wiki/Make-a-pull-request) and click on the play button where the video is provided..no video description plays after clicking on the play button.

### Expected Behavior

The play button should play the video but it doesn't.

### Screenshots/Videos

![Screenshot from 2023-11-27 01-24-10](https://github.com/oppia/oppia/assets/149883220/7b20cdf6-dea4-441a-9788-f268c951fc91)

### What device are you using?

Desktop

### Operating System

Linux

### What browsers are you seeing the problem on?

Chrome

### Browser version

119-stable

### Additional context

Having this video description would be good for the new comers

### Tips for developers

Before tackling the bug, please use `git bisect` (see https://git-scm.com/docs/git-bisect) to investigate which PR caused it (you only need to go back as far as commit https://github.com/oppia/oppia/commits/9a334e9). If you find the PR, leave a comment on this issue pointing to it, or just say that it happened before commit 9a334e9 if you could reproduce it there. This will help us fix the issue by reverting the faulty PR.

Also, if this is your first issue, please make sure to follow https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue and https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up before claiming it. Thanks!

**Comment by seanlip** [comment]
@sthoopidshrish I just played it, it works for me. I think it might be a connection issue and more generally an issue with GitHub-hosted assets. Can you try refreshing the page? 

If you still run into issues, please contact GitHub directly since this is probably an issue with their infrastructure. Thanks!
