### ISSUE TITLE
Add info to the wiki about how to find the commit which caused an issue.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-web-developer-docs#210]
@prafulbbandre has written a [document](https://docs.google.com/document/d/1xOmTf3P47bZCxwHnPd8vDoXa-mBbhMfqzwEQgfTKW3s/edit) called "Finding Bad Commits with the help of Git Blame and Git Bisect". This is very useful info that we can provide contributors, and we should probably add it to the wiki as a guide.

We should do the following:

- [x] Transfer the content to the Coding Guidelines > Debugging section in the wiki sidebar, in a new page called "How to find the commit which introduced a bug". (Done -- #219)
- [x] Link to this content from our general bug-fixing issue template. -- Done in https://github.com/oppia/oppia/pull/19457
- [x] Add the page https://github.com/oppia/oppia/wiki/How-to-find-the-commit-which-introduced-a-bug to the wiki sidebar. -- Done in https://github.com/oppia/oppia-web-developer-docs/pull/240

**Comment by satvshr** [comment]
Hey Sean,

I plan to add a line [here](https://github.com/oppia/oppia-web-developer-docs/blob/ee54c36d3c09f840b2ca5832c7eec50401cd6eab/Debugging.md?plain=1#L21) linking the issue to the Google Doc you mentioned. Additionally, I wanted to ask if you would like the document to be converted into a separate page following the [wiki](https://github.com/oppia/oppia/wiki/Wiki-style-guide) guidelines? I am a bit confused about what you mean by "Link to this content from our general bug-fixing issue template."

**Comment by seanlip** [comment]
@satvshr Please don't link to a doc; let's actually make a wiki page for this instead and link to it.

The last line refers to the last part of https://github.com/oppia/oppia/blob/develop/.github/ISSUE_TEMPLATE/1_bug_report_form.yml (the placeholder text in the last field).

Thanks!

**Comment by satvshr** [comment]
@seanlip can I work on this or is @prafulbbandre working on it?

**Comment by seanlip** [comment]
@satvshr You can work on this if you like. I'm assigning you, when can you make a PR by?

**Comment by satvshr** [comment]
@seanlip Sorry for not mentioning that, is the 2nd of Jan alright?

**Comment by satvshr** [comment]
> @seanlip Sorry for not mentioning that, is the 2nd of Jan alright?

Never mind I am already finished with the article, could you please tell me how I can add a link to the general bug-fixing issue template as mentioned in checkpoint 2?

**Comment by seanlip** [comment]
@satvshr You'll need to edit this file that I pointed you to earlier: https://github.com/oppia/oppia/blob/develop/.github/ISSUE_TEMPLATE/1_bug_report_form.yml (the placeholder text in the last field).

This involves making a PR to the oppia/oppia repository. So, completing this issue fully would entail two PRs, one to this repo and one to oppia/oppia.

**Comment by satvshr** [comment]
> @satvshr You'll need to edit this file that I pointed you to earlier: https://github.com/oppia/oppia/blob/develop/.github/ISSUE_TEMPLATE/1_bug_report_form.yml (the placeholder text in the last field).
> 
> This involves making a PR to the oppia/oppia repository. So, completing this issue fully would entail two PRs, one to this repo and one to oppia/oppia.

I can only do that once my pr is merged and a link to the article is created, so I will wait until that's done.

Edit: @seanlip should I just change the link here: `Before tackling the bug, please use `git bisect` (see https://git-scm.com/docs/git-bisect)` to the link to my article?

**Comment by seanlip** [comment]
@satvshr Yes and perhaps drop any stuff in the note there that's redundant with your article.

**Comment by satvshr** [comment]
> @satvshr Yes and perhaps drop any stuff in the note there that's redundant with your article.
How is this @seanlip?
Before addressing the bug, follow these steps: Use `git bisect` to identify the PR causing the issue (refer to https://github.com/oppia/oppia/wiki/How-to-find-the-commit-which-introduced-a-bug). If the bug occurred before commit [`c7db0fe`](https://github.com/oppia/oppia/commit/c7db0fe), use the [Python setup](https://github.com/oppia/oppia/wiki/Installing-Oppia/718fd4d0d9ba801142c02e98a499db26ed852c54) for `git bisect` (only back to commit [`9a334e9`](https://github.com/oppia/oppia/commits/9a334e9). For commits beyond that, use the Docker setup. If you identify the PR, comment on the issue with a link to it. If it happened before commit 9a334e9, mention that. Consider using `git blame` along with `git bisect` for more detailed insights during the investigation.

**Comment by seanlip** [comment]
I'd just say:

```
Before addressing the bug, please identify which PR caused the issue (you can follow the steps [here](https://github.com/oppia/oppia/wiki/How-to-find-the-commit-which-introduced-a-bug)). If you identify the PR, comment on the issue with a link to it. If not, mention the commit hash of the oldest commit you saw the bug on (and the month and year it was made in).
```

**Comment by satvshr** [comment]
> I'd just say:
> 
> ```
> Before addressing the bug, please identify which PR caused the issue (you can follow the steps [here](https://github.com/oppia/oppia/wiki/How-to-find-the-commit-which-introduced-a-bug)). If you identify the PR, comment on the issue with a link to it. If not, mention the commit hash of the oldest commit you saw the bug on (and the month and year it was made in).
> ```

The template being used now makes no sense but I felt there was a reason for that, this sounds way better and simpler. Thanks!

**Comment by seanlip** [comment]
@satvshr I was trying to find your new page just now but I had trouble doing that, and then realized it's not in the wiki sidebar. Could you please add it there too, with all the other debugging wiki pages? Thanks.

**Comment by seanlip** [comment]
@satvshr This looks like it's fully addressed. Thanks! I'm closing it as completed :)
