### ISSUE TITLE
Update Docker wiki regarding the use of WSL terminal for the windows users

### ISSUE THREAD

**Issue by Shivkant-Chauhan** [oppia/oppia-web-developer-docs#214]
Since Docker in Windows requires WSL for executing its commands (refer here: https://docs.docker.com/desktop/install/windows-install/#system-requirements). We should clearly state that WSL is also an pre-requisite for the Window Users and every `make` command in Docker Setup needs to be executed within the WSL terminal.

**Comment by seanlip** [comment]
Should also verify instructions for Docker on Windows (and update wiki as needed)
