### ISSUE TITLE
Missing screenshot of Github Blame on the contribution wiki

### ISSUE THREAD

**Issue by jaiakash** [oppia/oppia-web-developer-docs#215]
Hi, i was going through the contribution wiki to setup the project and noticed that one of the screenshot link was broken. 

Link - https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#notes

<img width="671" alt="Screenshot 2023-12-26 at 10 05 55 PM" src="https://github.com/oppia/oppia-web-developer-docs/assets/33419526/b041900b-1416-449b-b0f0-8e66ceef87ae">

Do let me know if can send a PR to add the image

**Comment by seanlip** [comment]
Hi @jaiakash -- yes, feel free to send a PR to this repo (oppia-web-developer-docs) if you like. Thanks!

**Comment by seanlip** [comment]
This seems to be fixed by the developer by changing their system DNS to 8.8.8.8 or 1.1.1.1.

See https://github.com/oppia/oppia-web-developer-docs/pull/217#issuecomment-1872270934
