### ISSUE TITLE
[BUG]: python2 installation error in ubuntu

### ISSUE THREAD

**Issue by rajeshkanugu** [oppia/oppia-web-developer-docs#216]
### Describe the bug

When I am trying to setup oppia in ubuntu and trying to install python2 I am getting not found error

### URL of the page where the issue is observed.

https://github.com/oppia/oppia/wiki/Installing-Oppia-%28Linux%3B-Python-3%29

### Steps To Reproduce

Follow the installation steps for oppia in wsl2
Then try to install python2

### Expected Behavior

python2 should get install correctly

### What device are you using?

Desktop

### Operating System

Windows

### What browsers are you seeing the problem on?

Chrome

### Browser version

120.0.6099.129

### Tips for developers

Before tackling the bug, please use `git bisect` (see https://git-scm.com/docs/git-bisect) to investigate which PR caused it. If the issue occurred before commit https://github.com/oppia/oppia/commit/c7db0fe, the most effective approach is to utilize the [Python setup](https://github.com/oppia/oppia/wiki/Installing-Oppia/718fd4d0d9ba801142c02e98a499db26ed852c54) for conducting a `git bisect` (You only need to go back as far as commit https://github.com/oppia/oppia/commits/9a334e9). If you need to perform a `git bisect` for any commit beyond that commit, the Docker setup will be suitable. If you find the PR, leave a comment on this issue pointing to it, or just say that it happened before commit 9a334e9 if you could reproduce it there. This will help us fix the issue by reverting the faulty PR.

Also, if this is your first issue, please make sure to follow https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue and https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up before claiming it. Thanks!

**Comment by rajeshkanugu** [comment]
I found the solution to the above one and was able to setup oppia successfully

**Comment by masterboy376** [comment]
> I found the solution to the above one and was able to setup oppia successfully

@kanugurajesh is it resolved  now?

**Comment by rajeshkanugu** [comment]
@masterboy376 yes the issue is resolved now I want to create a pull request to change it in the documentation so that developers do not face any trouble.

**Comment by seanlip** [comment]
@kanugurajesh What was the solution?

You're also welcome to make a PR to the wiki repo at  https://github.com/oppia/oppia-web-developer-docs/ if you like. Thanks!

**Comment by seanlip** [comment]
@kanugurajesh Friendly ping -- we'll probably close this issue if there is no solution forthcoming.

**Comment by rajeshkanugu** [comment]
@seanlip sorry for the late response there was a dependency error python2 is not available in ubuntu version I had to install python-minimal dependency to resolve the error.

**Comment by seanlip** [comment]
OK, thanks. Would you like to make a PR to the wiki repo at https://github.com/oppia/oppia-web-developer-docs/ to update the instructions for future contributors?

**Comment by kanugurajesh** [comment]
@seanlip I would like to make a Pr it would solve the following problems

1. python2 is not working in ubuntu

Solution

1. python2-minimal is working so I would like to change it

**Comment by seanlip** [comment]
OK, please provide a preview here of the exact changes you plan to make, and if they look good we can assign you. Thanks!

**Comment by kanugurajesh** [comment]
@seanlip sure I would like to make a pr

**Comment by rajeshkanugu** [comment]
@seanlip sure

**Comment by rajeshkanugu** [comment]
My Pr would solve the python2 dependency error in ubuntu I am proposing the following changes

I am planning to make changes to the .\Installing-Oppia-(Linux;-Python-3).md file.

I will change the installation step `sudo apt install python2` to `sudo apt install python-minimal`

![Screenshot 2024-01-08 113936](https://github.com/oppia/oppia-web-developer-docs/assets/120458029/d9f57a26-2d45-4f68-b443-8b09fdaaba76)

**Comment by rajeshkanugu** [comment]
@seanlip is the above one okay or do you want me to make any changes.

**Comment by seanlip** [comment]
@rajeshkanugu I just tried this out locally and it doesn't work for me:

```
$ sudo apt install python-minimal
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package python-minimal is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python2-minimal:i386 python2-minimal

E: Package 'python-minimal' has no installation candidate
```

**Comment by rajeshkanugu** [comment]
![Screenshot 2024-01-08 180827](https://github.com/oppia/oppia-web-developer-docs/assets/120458029/e6d85588-abc5-4d36-86b6-38891566179e)

**Comment by kanugurajesh** [comment]
![Screenshot 2024-01-08 180827](https://github.com/oppia/oppia-web-developer-docs/assets/77529419/7b74a2bf-a214-46a9-abbd-674b624eec48)

**Comment by kanugurajesh** [comment]
@seanlip I am able to install it

**Comment by kanugurajesh** [comment]
But when I was following the installation steps in the oppia docs I got errors and I fixed it this way

I fell that we can add python2-minimal, python-minimal, python2 we will ask the user to try all of these any of these can work for him

**Comment by seanlip** [comment]
Yup that's fine. I've assigned you, feel free to go ahead and make changes. Thanks!

**Comment by rajeshkanugu** [comment]
@seanlip @kanugurajesh is mine this account is on college gmail and It might expire and I dont want to lose my contributions. so i shifted to @kanugurajesh account can you please assign to that account. I want to continue contributing to oppia even in future.

**Comment by rajeshkanugu** [comment]
![Screenshot 2024-01-08 182750](https://github.com/oppia/oppia-web-developer-docs/assets/120458029/4e30d11f-6c85-4579-8b7b-263775362bfc)

**Comment by kanugurajesh** [comment]
@seanlip can you assign the issue to this account

**Comment by seanlip** [comment]
Just a note, you can assign multiple emails to one account. Go to your user dropdown in the top right and click on Settings > Emails. That might help solve the issue you are having.

In terms of assignment ... we'll typically assign to the same account that is commenting. So please try to use a consistent account everywhere, otherwise it will become confusing. You might also run into some issues with the CLA if you use a different account -- can you confirm after trying the steps in the first paragraph that you actually do want to switch to kanugurajesh?

**Comment by kanugurajesh** [comment]
I have been using @kanugurajesh account for opensource contributions from beginning , but I shifted it in middle. I have filled the CLA with my current gmail and account name. I want to maintain a single account. Can you please assign it to this account. I will be using only this account for future contributions.

**Comment by kanugurajesh** [comment]
@seanlip Thanks I will soon create a PR

**Comment by kanugurajesh** [comment]
@seanlip I have created the pullrequest #233
