### ISSUE TITLE
[ Oppia Web ] Scripts for runnning frontend tests in Docker Setup

### ISSUE THREAD

**Issue by DhairyaMajmudar** [oppia/oppia-web-developer-docs#222]
Add Scripts for running frontend tests in the Docker setup Wiki.

**Comment by DhairyaMajmudar** [comment]
Reference Wiki to be Update :- [Link](https://github.com/oppia/oppia/wiki/Installing-Oppia-using-Docker)

**Comment by gp201** [comment]
Duplicate https://github.com/oppia/oppia-web-developer-docs/issues/225
