### ISSUE TITLE
[ Oppia Web ] Add section on how to run tests in Docker

### ISSUE THREAD

**Issue by gp201** [oppia/oppia-web-developer-docs#225]
Update this [page](https://github.com/oppia/oppia-web-developer-docs/blob/develop/Installing-Oppia-using-Docker.md).
A new section called "Running tests" has to be added where the following make commands have to be added: [Makefile#L94-L221](https://github.com/oppia/oppia/blob/f2deedb6279dd0eed190307046eb872d23edff64/Makefile#L94-L221)
Running `make help` will provide you with more information on how to use the commands.

**Comment by shivang0-0** [comment]
Hey @gp201, I'm willing to work on this issue.
