### ISSUE TITLE
[Docker] Add step asking users to open localhost 8181

### ISSUE THREAD

**Issue by gp201** [oppia/oppia-web-developer-docs#227]
Make it clean in the instructions that the website can be accessed via localhost:8181 in this [section](https://github.com/oppia/oppia/wiki/Installing-Oppia-using-Docker#launching-the-development-server).
Add a step after `make run-devserver` asking users to open `localhost:8181` to view the websites.

**Comment by rajeshkanugu** [comment]
@gp201 can I work on this issue.

**Comment by kanugurajesh** [comment]
@gp201 I have created a PR #234 which solves your issue

I have added the following changes

I have added the step 

3. **Verify the development server is up**: Open your browser and navigate to `http://localhost:8181/`. You should see the Oppia development server running.

![Screenshot 2024-01-08 192927](https://github.com/oppia/oppia-web-developer-docs/assets/77529419/aecc44d1-fa20-4ce5-86d4-1efa9f4a0b1d)

Please tell me if there are any mistakes I can rectify them.

**Comment by kanugurajesh** [comment]
@gp201 I have made changes as per your requirements and created the pull request can you please check it.
