### ISSUE TITLE
[Docker]: Dockerized dev-server on 22.04 Ubuntu is leading to a 404 in any of the page under /learn/math

### ISSUE THREAD

**Issue by ghost** [oppia/oppia-web-developer-docs#232]
## Describe the bug:
It is observed that when a user is trying to visit any page under the /learn path a 404 error is being observed. 

## URL of the page:
https://www.oppia.org/learn/math

## Steps To Reproduce:
1. Start the Docker setup by  **make run-devserver** ( pls visit https://github.com/oppia/oppia/wiki/Installing-Oppia-using-Docker)
2. Click on the **Learn section** and then click **Basic Mathematics**

## Expected Behaviour:
Expected to be redirected to a page similar to Production page.

## Screenshots/Videos:
![Screenshot from 2023-12-21 06-49-01](https://github.com/oppia/oppia/assets/113231164/96ef6f0c-76ff-4a5b-b5f8-5bbd3401f1cf)

## What device you are using?
Desktop

## Operating System :
Linux Ubuntu 22.04 LTS

## Tips for Developers:

Before tackling the bug, please use **git bisect** (see https://git-scm.com/docs/git-bisect) to investigate which PR caused it. If the issue occurred before commit https://github.com/oppia/oppia/commit/c7db0fe, the most effective approach is to utilize the [Python setup](https://github.com/oppia/oppia/wiki/Installing-Oppia/718fd4d0d9ba801142c02e98a499db26ed852c54) for conducting a **git bisect** (You only need to go back as far as commit https://github.com/oppia/oppia/commits/9a334e9). If you need to perform a **git bisect** for any commit beyond that commit, the Docker setup will be suitable. If you find the PR, leave a comment on this issue pointing to it, or just say that it happened before commit https://github.com/oppia/oppia/commit/9a334e9bde1d3d10e3b69dcd461d3e649733b0c0 if you could reproduce it there. This will help us fix the issue by reverting the faulty PR.

Also, if this is your first issue, please make sure to follow https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue and https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up before claiming it. Thanks!

**Comment by Asif-Sheriff** [comment]
@rijuoddusual1999 Interesting I installed oppia locally using pyenv but I am getting the same error

I initially thought it was an installation error on my part
![image](https://github.com/oppia/oppia/assets/130328580/a3ea279d-6f6d-4546-b710-22d7d0fc5bba)

**Comment by ghost** [comment]
Yes, @Asif-Sheriff getting the issue in the Python setup too. Pretty sure the issue got created in the PRs between last 3-4 days as  the Python setup was running fine before.

![Screenshot from 2023-12-21 22-22-52](https://github.com/oppia/oppia/assets/113231164/19aa3bc5-b7db-4660-aca1-ef632b1dd015)

I am trying to git bisect but hitting hard on my ram. Will update if I find the commit.

**Comment by Nik-09** [comment]
Hi @rijuoddusual1999, we need to create a Math classroom before accessing it.
There are two ways to create a classroom:
A: 
1. Assign the admin role from the admin roles tab 
2. Create dummy classroom from the admin activities tab
3. Navigate to math classroom (`/learn/math`)

B:
1. Assign the admin role from the admin roles tab 
2. Create Math classroom from the classroom admin page (`/classroom-admin`)
3. Navigate to math classroom (`/learn/math`)

Please let me know if you have further questions.

**Comment by Ykumar1415** [comment]
Yes, it is working fine in my local dev environment.  @rijuoddusual1999 can you re-varify this issue?

**Comment by ghost** [comment]
Hii @Nik-09 @Ykumar1415 Can you pls share the screenshot for /learn/math. Every other page is working mostly fine except the /learn/math on my machine, interesting thing is that /learn/math was working fine few days ago.  Let me reset head to the older version and verify. One other issue can be npm issue which may occur due to using wrong version but there is no specific version required in the docs. Let me just check.

Also can you kindly pls verify the page under docker setup also


![Screenshot from 2023-12-23 07-06-27](https://github.com/oppia/oppia/assets/113231164/555e0d3b-0caf-4189-a53c-f09b8d451b26)

![Screenshot from 2023-12-23 07-06-40](https://github.com/oppia/oppia/assets/113231164/2e1949b9-b382-4dc7-b126-ee4fe1d37b3e)

**Comment by Nik-09** [comment]
Hi, @rijuoddusual1999 I am not getting the relationship between the 'setup issues' and 'math classroom page loading'. Can you please enumerate the steps that you are performing to get into the math classroom?
Please provide the steps in detail something like - "Visited Page X load Y...".

Thanks.

**Comment by ghost** [comment]
Heh hii @Nik-09, just try to do a fresh setup from scratch again and then visit /learn/math page. Yesterday I tried to reset the head to *https://github.com/oppia/oppia/commit/9a334e9bde1d3d10e3b69dcd461d3e649733b0c0* but the page feature was not there yet as it was introduced in the later commits.


![Screenshot from 2023-12-24 10-07-52](https://github.com/oppia/oppia/assets/113231164/3ce1afac-5669-456f-9d3b-1103132c866e)

Pls click on **Learn** followed by **Basic Mathematics**

**Comment by Nik-09** [comment]
Yes, I know @rijuoddusual1999. 
Initially, the "/learn/math" classroom page functioned as a default page, obviating the necessity for the explicit creation of a classroom. However, there has been a recent development mandating the creation of a classroom through the "/classroom-admin" page to ensure accessibility to the math classroom.
I have mentioned the steps on how to create a classroom, could you confirm whether you have followed these steps accordingly?
([ref link](https://github.com/oppia/oppia-web-developer-docs/issues/232))

- Maybe share a screen recording of the steps that you are following. 
- Share a screenshot of the page: http://localhost:8181/classroom-admin

**Comment by ghost** [comment]
Hii @Nik-09  I followed your steps earlier but while assigning the admin role the role edit options was fetching error related to binding, I raised one thread in the Discussions(https://github.com/oppia/oppia/discussions/19332) .   

Here is the setup video link below:

https://drive.google.com/file/d/19ily6IGUTza_wc2u1xIHKC07Vr7ylrqF/view?usp=sharing

And also http://localhost:8181/classroom-admin is throwing a 401 Unauthorized error as I am not able to assign admin roles due to the error mentioned in Discussion , I will be attaching the snippet below:

![Screenshot from 2023-12-24 14-06-33](https://github.com/oppia/oppia/assets/113231164/7d64c751-15c6-4d04-9fed-653580391a0c)


Thank You

**Comment by Nik-09** [comment]
> Hi @rijuoddusual1999, we need to create a Math classroom before accessing it. There are two ways to create a classroom: A:
> 
> 1. Assign the admin role from the admin roles tab
> 2. Create dummy classroom from the admin activities tab
> 3. Navigate to math classroom (`/learn/math`)
> 
> B:
> 
> 1. Assign the admin role from the admin roles tab
> 2. Create Math classroom from the classroom admin page (`/classroom-admin`)
> 3. Navigate to math classroom (`/learn/math`)
> 
> Please let me know if you have further questions.

Add admin role to yourself from the admin page then try to access the classroom-admin page (Step 1 of A or B)

**Comment by ghost** [comment]
@Nik-09 I was not able to assign admin role as the role editor is not working which I mentioned in the discussion (https://github.com/oppia/oppia/discussions/19332) due to an already pre existing issue with the Google App Engine Dev Server failing to bind to the address 0.0.0.0:8181 as mentioned by @hrshkshri. 


So @seanlip @Nik-09 should I close this issue for now ? as the page should be accessed through the "/classroom-admin" page

**Comment by hrshkshri** [comment]
Hey @rijuoddusual1999,
I have answered the problem you are facing with. #19332 

Also, this particular issue doesn't exist and has no relation with oppia setup. I think we can close this issue now ( cc @seanlip  for confirmation )

**Comment by seanlip** [comment]
@hrshkshri Would it be possible to update the setup/installation wiki page to explain how to get /learn/math working first (after installation)? Then we can close the issue.

**Comment by hrshkshri** [comment]
> @hrshkshri Would it be possible to update the setup/installation wiki page to explain how to get /learn/math working first (after installation)? Then we can close the issue.

Yeah sure we can do that.
as @Nik-09 mentioned [here](https://github.com/oppia/oppia-web-developer-docs/issues/232)

**Comment by seanlip** [comment]
OK, let's create the wiki page; once that's done we can close this issue. (But if we don't do that, then this question will keep coming up again and again.)

**Comment by Nik-09** [comment]
I will create the wiki page for the classroom. I am assigning this issue to myself.

**Comment by hrshkshri** [comment]
Hey @Nik-09 
I have opened the [issue](https://github.com/oppia/oppia-web-developer-docs/issues/218) at [`oppia-web-developer-docs`](https://github.com/oppia/oppia-web-developer-docs) repo regarding the same.

And was starting to work on [issue](https://github.com/oppia/oppia-web-developer-docs/issues/218).

I just wanted to confirm if assigning issues at `oppia-web-developer-docs` repo is the right way to go further for updating the wiki page.

> I will create the wiki page for the classroom. I am assigning this issue to myself.

**Comment by Nik-09** [comment]
Yes, @hrshkshri I agree, can you please share the PR opening date, since this is an urgent issue?
Thanks

**Comment by hrshkshri** [comment]
@Nik-09 I would be able to open a PR by tomorrow for sure
Thanks

**Comment by gp201** [comment]
Transferred this issue to [oppia-web-developer-docs](https://github.com/oppia/oppia-web-developer-docs) since it's a wiki issue.

**Comment by gp201** [comment]
@hrshkshri is this issue completed?

**Comment by hrshkshri** [comment]
> @hrshkshri is this issue completed?

Yes @gp201

**Comment by gp201** [comment]
Fixed by #229
