### ISSUE TITLE
Modify all Wiki pages by adding an alternative Docker command for each Python command.

### ISSUE THREAD

**Issue by gp201** [oppia/oppia-web-developer-docs#236]
All commands in the wiki pages must be updated to have an alternative docker command
Format:
Python:
```
cmd
```
Docker:
```
cmd
```

**Comment by shivang0-0** [comment]
Hi @gp201, I would like to work on this issue.

**Comment by jaiakash** [comment]
Hi @gp201, I would like to work on this.

**Comment by gp201** [comment]
@jaiakash any updates?

**Comment by 0xV0YD** [comment]
hi @gp201

**Comment by rahat2134** [comment]
@gp201 please assign this to me.

**Comment by rahat2134** [comment]
@gp201  I will do it asap.

**Comment by gp201** [comment]
@rahat2134 This issue has already been assigned. However, feel free to take a look at any other issue.
