### ISSUE TITLE
Fix the wiki guidance for testing feature flags.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-web-developer-docs#245]
@StephenYu2018 raised a concern on the Contributor Dashboard team group chat along the following lines:

"On the subject of feature flags in backend tests, the instructions at https://github.com/oppia/oppia/wiki/Launching-new-features#backend tells me to "Clear the registry" before creating a mock feature flag. However, none of the code snippets provided show how exactly that should be done. While I could set the registry to an empty dictionary before creating the mock, this would mutate state that is shared amongst tests that are running in parallel."

It seems that the instructions on [this page](https://github.com/oppia/oppia/wiki/Launching-new-features#backend) are incorrect/unclear -- we probably need to fix them. This ties in with the current work that is being done to remove the registry entirely and improve the test framework for feature flags detailed in [this TDD](https://github.com/oppia/oppia-web-developer-docs/issues/245). /cc @lkbhitesh07

**Comment by seanlip** [comment]
@lkbhitesh07 Just to check, is this done? If so please link the PRs, thanks.

**Comment by Ash-2k3** [comment]
I think this PR might be it ? https://github.com/oppia/oppia-web-developer-docs/pull/262

**Comment by lkbhitesh07** [comment]
Oh!
I somehow missed the comment. We can close this issue, Thanks @Ash-2k3.
