### ISSUE TITLE
Feature flag wiki contains outdated information

### ISSUE THREAD

**Issue by Nik-09** [oppia/oppia-web-developer-docs#273]
For adding a new feature flag, the wiki page guides changes in some code snippets that are not currently present in the codebase (probably they were present in the past).

Reference wiki section: https://github.com/oppia/oppia/wiki/Launching-new-features#modifying-unit-tests-to-account-for-the-creation-of-the-new-flag

Expected: The wiki should contain the updated information.

**Comment by seanlip** [comment]
@lkbhitesh07 Assigning this to you per the discussion in the release task force meeting, thanks!

**Comment by lkbhitesh07** [comment]
Thanks @Nik-09, I think you are correct. We do not require the section for frontend unit test, the reason being is that all the feature-flags are configured in the backend and I am not sure if it is possible in the frontend tests to check if the listed feature-flags have been removed or added in the backend.
cc/- @seanlip 
Thanks

**Comment by seanlip** [comment]
@lkbhitesh07 I think that's not correct -- the frontend tests can't check what the status of the backend is, so they'd still need to mock the calls, right? (Not from sessionStorage, but from whatever call is actually made to the backend to get the values of the feature flags.)

So I think some explanation of how to do frontend unit testing with feature flags is still needed...

**Comment by lkbhitesh07** [comment]
Oh! I am sorry for not being clear @seanlip, that is not what I meant. We still have the [section](https://github.com/oppia/oppia/wiki/Launching-new-features#writing-unit-tests-for-gated-features) for adding the unit tests for both frontend and backend to test the changes you do for feature flags. We have one [section](https://github.com/oppia/oppia/wiki/Launching-new-features#modifying-unit-tests-to-account-for-the-creation-of-the-new-flag) that tells users to add a feature flag to the list to test the functioning of session storage. I think we can avoid this section.
Thanks

**Comment by lkbhitesh07** [comment]
Raised a PR - https://github.com/oppia/oppia-web-developer-docs/pull/282
Thanks

**Comment by seanlip** [comment]
Thanks @lkbhitesh07, merged. But next time please make sure your PR has the right title starting with "Fix #..." so that this issue can get closed when it's merged.
