### ISSUE TITLE
Update Documentation for Migration of Acceptance Tests to TypeScript.

### ISSUE THREAD

**Issue by rahat2134** [oppia/oppia-web-developer-docs#280]
The acceptance tests in our codebase have recently undergone migration from JavaScript to TypeScript by :
https://github.com/oppia/oppia/pull/19877
 However, the corresponding documentation on the wiki page still reflects procedures and examples based on JavaScript implementations. To ensure alignment with current practices and to facilitate developers' understanding and utilization of the acceptance testing framework, it's crucial to update the documentation to showcase TypeScript implementations and best practices. This update will enhance clarity, readability, and maintainability of the documentation, thereby improving collaboration and onboarding processes for team members and contributors.

**Comment by rahat2134** [comment]
@seanlip assign this issue to me. Will raise PR as soon as possible. Thanks.

**Comment by seanlip** [comment]
Sure, go for it, thanks!
