### ISSUE TITLE
Change "Note" and "Warning" Notations to be more noticeable.

### ISSUE THREAD

**Issue by gp201** [oppia/oppia-web-developer-docs#29]
Move all instances of:

**Note:** While #1 above is only for those having MacOS >= 12.3, #2 and #3 should be done by everyone using a Mac for setting up Oppia.
to 
> **Note**
> While #1 above is only for those having MacOS >= 12.3, #2 and #3 should be done by everyone using a Mac for setting up Oppia.

```
> **Note**
> While #1 above is only for those having MacOS >= 12.3, #2 and #3 should be done by everyone using a Mac for setting up Oppia.
```

and

Warning: {text}
to 
> **Warning**  
> {text}

```
> **Warning**  
> {text}
```

**Comment by SD-13** [comment]
Hi @U8NWXD @gp201 , please let me know if you guys are working on this or not so that I can take this one. Thanks,

**Comment by U8NWXD** [comment]
AFAIK no one is working on this right now. I think the right way to do this is probably to create a linter for it. wdyt @gp201?

**Comment by SD-13** [comment]
Okay, I will look into it and reach out here if I have any doubts. Also, I am assigning this issue to me.

**Comment by SD-13** [comment]
Hey @U8NWXD @gp201 what do you think about using [super linter](https://github.com/marketplace/actions/super-linter) for this?

**Comment by U8NWXD** [comment]
@SD-13 Super-Linter just provides a way to use other third-party linters. Which of those third-party linters would you want to use? Note that we need to vet all dependencies, including linters, to make sure they are well-maintained and don't introduce security issues

**Comment by SD-13** [comment]
> @SD-13 Super-Linter just provides a way to use other third-party linters. Which of those third-party linters would you want to use? Note that we need to vet all dependencies, including linters, to make sure they are well-maintained and don't introduce security issues

Sorry, I got the wrong idea. Yeah, keeping that in mind I am trying to use [this](https://github.com/avto-dev/markdown-lint) linter. Will make a PR soon.
