### ISSUE TITLE
Update Acceptance test wiki with mobile acceptance test info.

### ISSUE THREAD

**Issue by rahat2134** [oppia/oppia-web-developer-docs#292]
Due to PR https://github.com/oppia/oppia/pull/19938/files, Mobile Acceptance tests has been successfully added in oppia now.
So, wiki of acceptance need to be updated to help the developers/contributors to write acceptance tests for mobile and other info about mobile acceptance tests.

**Comment by rahat2134** [comment]
@seanlip  Please take a look. If the issue requires attention. I raised the concern as I have also encountered difficulties when writing tests for mobile. Thank you :)

**Comment by seanlip** [comment]
@rahat2134 Sure, what changes do you want to make? Feel free to self-assign if you want to work on it, I think @jnvtnguyen might also be able to help review (Justin, is that ok?)

Thanks.

**Comment by rahat2134** [comment]
@seanlip I do not have access to self-assign in this repository.

**Comment by seanlip** [comment]
@rahat2134 OK. Then I suggest that you answer my question in the previous comment, and then I can assign you.

**Comment by rahat2134** [comment]
@seanlip PTAL.
Some of the changes I was thinking of -> 
1) How to implement desktop and mobile acceptance tests in a single utils file with the help of conditions.
For eg: <img width="644" alt="Screenshot 2024-03-27 at 3 56 58 PM" src="https://github.com/oppia/oppia-web-developer-docs/assets/136263179/5fd3a837-d5c2-4412-a855-18bfb79904fb">

2) How to run mobile acceptance
 tests locally.

3) Also, since console errors are also now been added, so if there is any error which doesn't need attention right now and can be ignored, then how to ignore that?
etc

**Comment by seanlip** [comment]
OK, thanks @rahat2134. Go for it!

**Comment by jnvtnguyen** [comment]
@seanlip @rahat2134 Yes I can review. Thanks
