### ISSUE TITLE
Deprecate the script python -m scripts.populate_sample_contributor_data.

### ISSUE THREAD

**Issue by Ash-2k3** [oppia/oppia-web-developer-docs#296]
The script (`python -m scripts.populate_sample_contributor_data`) used to populate data in the contributor dashboard seems to be encountering issues and is generating errors for the contributors. Following our discussion in the group chat, we have decided to deprecate the script and update the [wiki](https://github.com/oppia/oppia/wiki/Contributor-dashboard#local-development) with a manual method for populating the contributor dashboard with test data.

Some discussions where users encountered problems with running the scripts can be found here: https://github.com/oppia/oppia/discussions/19008, https://github.com/oppia/oppia/discussions/19299.

The manual steps for populating the contributor dashboard are as follows:

1. Create two separate users.Assign one of them the roles of curriculum admin and translation admin.
2. Generate the data from /admin-page.
3. Assign the other user the role of translation reviewer from /contributor-admin-dashboard.

**Comment by Ash-2k3** [comment]
Hi @seanlip, I wanted to confirm if we want to remove the usage of this script permanently or until it's brought back to work properly as expected?


/cc @chris7716 for info

**Comment by seanlip** [comment]
I suggest we drop it permanently, and if we reinstate the functionality, we do this using a button in the Admin > Activities page rather than as a separate script. @chris7716 @Ash-2k3 does this sound good?

If you agree, it might be worth filing an issue on oppia/oppia to track that.

**Comment by Ash-2k3** [comment]
We already have something similar right, as mentioned in step 2 of the manual generation. It creates 3 translatable explorations and skills for which we can suggest practise questions.

The extra step would be to create a new user with translation reviewer/question reviewer rights.

**Comment by seanlip** [comment]
Ah ok, then that sounds fine to me to do manually, and I don't think we need to reinstate the script, thanks.

@chris7716 @StephenYu2018 do you agree?

**Comment by seanlip** [comment]
Also @Ash-2k3 are you able to take this up? I assigned you, but feel free to unassign if you can't, thanks.

**Comment by chris7716** [comment]
I agree with that. I think in the new Admin button script, we will have to set up data that are required to question related stuff as well.

**Comment by StephenYu2018** [comment]
@seanlip I agree with dropping the script entirely.

**Comment by Ash-2k3** [comment]
It looks like @amaanlari is working on an issue related to populating data for CD local testing. https://github.com/oppia/oppia/issues/14698. I think, I will wait until mentioned issue is solved, so that we can mention it in wiki.

(Also, @amaanlari please comment in this issue thread once your PR gets merged so that we can update the wiki in accord. Thanks.)

**Comment by Ash-2k3** [comment]
FYI, filed an issue to remove code for this script https://github.com/oppia/oppia/issues/20131. I think it might be a GFI as well.

**Comment by seanlip** [comment]
> It looks like @amaanlari is working on an issue related to populating data for CD local testing. [oppia/oppia#14698](https://github.com/oppia/oppia/issues/14698). I think, I will wait until mentioned issue is solved, so that we can mention it in wiki.
> 
> (Also, @amaanlari please comment in this issue thread once your PR gets merged so that we can update the wiki in accord. Thanks.)

@Ash-2k3 I think it is important to keep the wiki properly up-to-date. If the current info on it is incorrect, please remove it and replace it with manual steps until @amaanlari's PR gets in. Thanks.

**Comment by Ash-2k3** [comment]
Alright, I have opened a PR for this: https://github.com/oppia/oppia-web-developer-docs/pull/307
