### ISSUE TITLE
Add a wiki page explaining how to quickly load data into the development server.

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-web-developer-docs#30]
For solving certain issues, developers may need to populate the local server datastore with a bunch of skills/topics/lessons/users/etc. I keep seeing new developers asking questions on how to do this (e.g. how to get a translation into their local contributor dashboard page so that they can try reviewing it, as a first step towards fixing a bug in the review process).

We should add instructions for how to do this, so that issue reproduction instructions can point to them. It would be nice to define (and implement buttons in the /admin Activities tab for) a set of "standard configurations" that we maintain for this purpose -- these configurations can cover different types of data (e.g. LaCE-related vs contributor-dashboard related) and be optimized for different things (e.g. multiple classrooms vs 1000 items for load testing vs single copy of each entity).

**Comment by U8NWXD** [comment]
I think we used to have this option in the admin tab. Did we get rid of it?

**Comment by seanlip** [comment]
We do have it still, it's in the Activities tab in /admin, but only on the local dev server. We might need easily-linkable instructions for how to use this though.

Also, it's not clear whether all the functionality that devs would like to have in "easy reach" is already present there or not -- I think things have just been added there ad hoc and it might be nice to do this more systematically.

**Comment by Shivkant-Chauhan** [comment]
@chris7716 please update the project board with the expected merge date..

**Comment by Shivkant-Chauhan** [comment]
hi @chris7716, can you please update the project board with the expected merge date or when you plan to open a PR on this. thanks!

**Comment by chris7716** [comment]
Done

**Comment by gp201** [comment]
@chris7716 Moved this to high priority since more than 2 contributors have opened discussions asking how to load data.

- https://github.com/oppia/oppia/discussions/17557

**Comment by U8NWXD** [comment]
@chris7716 when do you expect to fix this issue (seeing as the current target date is today)?

**Comment by chris7716** [comment]
I hope to open a PR by EOD 25th as we discussed in the onboarding team meeting.

**Comment by U8NWXD** [comment]
@chris7716 that date (Apr 25) has passed now. Could you please give an updated estimate?

**Comment by chris7716** [comment]
@U8NWXD Sorry I have been feeling sick for the past couple of days. I opened a PR. Could you please let me know what more I can add?
