### ISSUE TITLE
Document Typical Test Execution Duration of all type of tests.

### ISSUE THREAD

**Issue by Akhilesh-max** [oppia/oppia-web-developer-docs#302]
I observed that the frontend test execution on my MAC M1, was taking around 30-40 minutes. I initially thought this to be normal due to a lack of documentation specifying the expected duration. However, I later discovered that this was due to the lack of optimization of Chrome for arm64 (it’s recently been fixed, possibly because of the new release of Chrome). On other devices (may not be all), the tests typically run for about 3-5 minutes.

For the benefit of newcomers and to prevent any confusion in the future, it may be a good idea to document the typical test execution time of all type of tests we can run locally, assuming sufficient resources are available. This will provide a benchmark for what is considered ‘normal’, allowing developers to identify any potential issues or anomalies in test execution time.

Please note that the actual duration may vary based on the specific test and device resources.

**Comment by agallop** [comment]
Here is a recent run on my Mac, up-to-date with the develop branch. 

System Specs:
<img width="366" alt="image" src="https://github.com/oppia/oppia-web-developer-docs/assets/9313126/950fc131-13d1-4913-b74b-44dca63afb41">

**Comment by Akhilesh-max** [comment]
@agallop, could you please try running e2e tests and let me know the usual duration for completion? Also, please specify the test suite you ran.
