### ISSUE TITLE
Provide guidance on communicating questions 

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-web-developer-docs#31]
Communication is an issue that keeps coming up in mentoring contributors. It may be worth having a page or several to provide guidance on how to do this well, since it isn't necessarily obvious. Some of these could be linked from the onboarding instructions/pages as well.

1) A specific pattern that seems to arise commonly is when developers write emails or solicit help with something along the lines of "I have an error", which doesn't allow the recipient to help without a lengthy back-and-forth requesting further information. It would help to have info about "how to communicate an error properly" and "where to communicate it" (probably GitHub Discussions) -- this seems like a good thing to link to from the setup instructions. Some of this guidance could include:

```
When writing emails reporting an error:
    - Don't say "it happens when I run X". Start with the actual command you ran (copy/paste it).
    - Include the specific error message
    - Share the specific steps that the recipient should follow in order to repro the mentioned error
    - Explain what you've tried and what conclusions you've drawn, if any. (Providing a [debugging doc](https://github.com/oppia/oppia/wiki/Debugging-Docs) may help.)
```

2) In our "build your skills" section (and possibly in other relevant pages), it might be useful to recommend the technical writing courses at https://developers.google.com/tech-writing/overview -- these might be helpful when writing comments and technical documentation like design docs. /cc @sagangwee

**Comment by U8NWXD** [comment]
On our wiki page for how to get help, we provide a template for asking questions: https://github.com/oppia/oppia/wiki/Get-help#how-to-ask-good-questions

**Comment by U8NWXD** [comment]
@seanlip could you elaborate on what would help in addition to the existing page? Is this a discoverability issue, or does the page also need changes?

**Comment by seanlip** [comment]
Two thoughts (for (1), at least):

- Yes, I think it is a discoverability issue -- "how to communicate" should probably be one of the first things we explain, given that folks may already need to do this as early as the installation step in the setup guide.
- The guidance on the linked page seems like it applies to GitHub conversations (especially in the templates for "How to ask a setup question" and "How to ask a general question"). So I don't think we currently give much guidance on how to write emails and/or ask questions using chats + GitHub Discussions (though, for the latter, it might be better to include a reminder directly in GitHub Discussions itself since that's where folks will see it -- /cc @gp201).

**Comment by gp201** [comment]
Currently, there are no templates for GitHub Discussions, so we won't be able to add it as a reminder to Github discussions. But it looks like its on the roadmap: https://github.com/community/community/discussions/2838

**Comment by seanlip** [comment]
Hm. Maybe a pinned discussion topic / announcement perhaps? Not sure.

**Comment by U8NWXD** [comment]
Deassigning myself since I'm not working on this currently, but it's still on the dev workflow team's todo list

**Comment by mkos11** [comment]
Be specific: Make sure your question is specific and to the point. Avoid being vague or unclear, as this can lead to misunderstandings or unhelpful responses.

Provide context: Give some background information on what you're working on or what you're trying to accomplish. This will help others understand your question and provide a more informed response.

Use simple language: Avoid using technical jargon or language that may be difficult for others to understand. Use simple and clear language that is easy to comprehend.

Be polite and respectful: When asking a question, be polite and respectful. Avoid being confrontational or aggressive, even if you are frustrated with the issue. A friendly and respectful tone can encourage others to respond positively.

Ask one question at a time: If you have multiple questions, it's better to ask them one at a time. This makes it easier for others to understand your question and provide a specific response.

Proofread your question: Before submitting your question, proofread it for any spelling or grammar errors. A well-written question is more likely to receive a helpful response.

Follow up if necessary: If you don't receive a response or if the response doesn't fully answer your question, don't be afraid to follow up. Politely ask for clarification or more information if needed.

By following these tips, you can effectively communicate your questions and increase the likelihood of receiving a helpful response

**Comment by vaishnavi192** [comment]
Hey @U8NWXD @seanlip @gp201 I started understanding codebase of oppia since november. So i am new contributor and I can add instructions from my experience of getting difficulties in the starting. I would like to take up this issue. Is this issue open for anyone or only developer workflow team?

**Comment by seanlip** [comment]
@vaishnavi192 All issues are open for anyone, but we will only assign an issue once we have a clear description of what files you will change and what fixes you plan to make. See our [instructions for claiming an issue](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue).

**Comment by vaishnavi192** [comment]
![image](https://github.com/oppia/oppia-web-developer-docs/assets/117008958/2586dec5-eaec-4c1d-a929-aa14a62cfeb0))
![image](https://github.com/oppia/oppia-web-developer-docs/assets/117008958/390cd04c-09fc-4040-9ad7-641fe25bfe7e)
Hey @seanlip have a look at it. I created a "asking-questions-effectively.md" page. and created a basic guideline for now. I was thinking to add all communication channels before telling how to communicate on it. Can you suggest if I should add that or not as it is already present in [this](https://github.com/oppia/oppia/wiki/Get-help#communication-channels) page.

**Comment by seanlip** [comment]
@vaishnavi192 This is a good start, some thoughs:
- It's great that you found the "How to get help" page! I suggest augmenting that page rather than creating a completely separate new page. Feel free to modify it as needed, e.g. it might be worth putting GitHub Discussions at the top and email at the bottom since we use that less often now.
- In general let's try to avoid duplication, so don't mention a point if it's already mentioned in the wiki page you linked to.
- We should make sure to link to this page from the getting started instructions at relevant places (installation? tackling the first issue? etc.) so that it's discoverable by developers.

Could you please have another go, per the above? Thanks!

**Comment by vaishnavi192** [comment]
Hey @seanlip 
![image](https://github.com/oppia/oppia-web-developer-docs/assets/117008958/1d5904ed-e756-4a7f-b05b-491d942bf645)
![image](https://github.com/oppia/oppia-web-developer-docs/assets/117008958/97c91f08-e1db-4799-a85b-fe6911a85a86)
![image](https://github.com/oppia/oppia-web-developer-docs/assets/117008958/4c62fa3a-ce42-49f0-8a75-9797fa0acc15)
![image](https://github.com/oppia/oppia-web-developer-docs/assets/117008958/41b3fe62-aaf8-4e9b-8c85-ca656afbf790)
![image](https://github.com/oppia/oppia-web-developer-docs/assets/117008958/bd10337b-f255-4e68-8110-b87ba368579b)

I added the links in "installing oppia" page, "general contributor guideline/home" page, "contributing to oppia:good first issues" page  
I will delete the page which I created before as I have made changes in "get help" page

**Comment by seanlip** [comment]
@vaishnavi192 Thanks. This needs more work, but let's go ahead and assign you to this issue and you can make a PR. We'll do further edits in PR review. Thanks!

**Comment by vaishnavi192** [comment]
Hey @seanlip I created PR.....Thanks a lot for assigning me my first issue!! I was trying since many days to solve issues but was not able to do that, I hope I will learn more and solve big issues as well in future and continue contributing to oppia!

**Comment by gp201** [comment]
> Currently, there are no templates for GitHub Discussions, so we won't be able to add it as a reminder to Github discussions. But it looks like its on the roadmap: [community/community#2838](https://github.com/orgs/community/discussions/2838)

FYI, Discussion templates are out. https://github.com/oppia/oppia/tree/develop/.github/DISCUSSION_TEMPLATE It would be a good idea to link the wiki or briefly mention what we expect from the dev.

**Comment by seanlip** [comment]
Thanks @gp201!

I think this issue is addressed by @vaishnavi192's PR, so I'm closing it. I also filed an issue to create more templates for GitHub Discussions here: https://github.com/oppia/oppia/issues/20019.
