### ISSUE TITLE
Documentation Issue on #how-to-tackle-good-first-issues

### ISSUE THREAD

**Issue by smtirike02** [oppia/oppia-web-developer-docs#310]
Hi, I noticed in the documentation that in the **[Good first issues for new contributors](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#how-to-tackle-good-first-issues)** that when you click on Contributor Dashboard, It shows that the view no longer exists? I think that this should be removed so that users are not confused can be redirected to this instead:  [Good First Issues Contributor Experience Team](https://github.com/orgs/oppia/projects/18/views/14l)

**https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#how-to-tackle-good-first-issues**

![IMG_4265](https://github.com/oppia/oppia/assets/121672080/cdf089cf-3c76-4882-a201-d63257fad408)
![IMG_4263](https://github.com/oppia/oppia/assets/121672080/75d42e6b-9bfc-4b9a-b789-2f07992138db)

**Comment by seanlip** [comment]
Many thanks for reporting this, @smtirike02. Sorry for the inconvenience -- this is now fixed by https://github.com/oppia/oppia-web-developer-docs/pull/311!
