### ISSUE TITLE
Deprecate the Onboarding Mentor Program.

### ISSUE THREAD

**Issue by Ash-2k3** [oppia/oppia-web-developer-docs#319]
Per the discussion with the welfare team, we are planning to deprecate the Onboarding Mentor Program as we don't have the bandwidth to assign mentors to all the folks and also most of the queries asked from mentees can be found in wiki or resolved via github discussions.

**Comment by HardikGoyal2003** [comment]
Hey @Ash-2k3 please can you assign this issue to me!?

**Comment by Ash-2k3** [comment]
Completed in https://github.com/oppia/oppia-web-developer-docs/pull/321
