### ISSUE TITLE
Provide guidance for non-technical users about how to file issues

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-web-developer-docs#32]
Non-developers in our community (e.g. designers, translators, etc.) are generally not familiar with how to file an issue on Oppia's GitHub. It would be nice to have a page that's dedicated to explaining how to do this. 

This page should be aimed at users who have never used GitHub, and start by explaining how to create a GitHub account and then what to do from there. It can reference the [GitHub instructions](https://docs.github.com/en/issues/tracking-your-work-with-issues/creating-an-issue#creating-an-issue-from-a-repository), but should ideally be customized to the Oppia workflow.

**Comment by gp201** [comment]
Based on the type of issues we're expecting from them, we could take advantage of the [issue forms feature in GitHub](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms).

**Comment by gp201** [comment]
The wiki page will have to give a brief description of the Github workflow (Issue -> triage -> PR)

**Comment by U8NWXD** [comment]
@gp201 I think this has been solved by our issue forms. wdyt?

**Comment by gp201** [comment]
We still need to create a page on how to get started with GitHub. Or do we have that?

**Comment by U8NWXD** [comment]
I'm not convinced we need a wiki page for this. Our non-developers may not be coders, but we can still trust that they are comfortable with typical online accounts. If they click on "New issue" on the GitHub issues page, they'll be taken to what seems to me to be a pretty intuitive account creation flow:

![Screen Shot 2022-11-13 at 13 13 03](https://user-images.githubusercontent.com/19878639/201539228-ded02dc0-cef7-4396-af30-5dee0f65a199.png)
![Screen Shot 2022-11-13 at 13 16 49](https://user-images.githubusercontent.com/19878639/201539229-891bda02-1ee6-47c1-9b84-f6f25c9a0ff4.png)

Creating a wiki page to walk users through this flow seems to me like a step toward being almost patronizing. It'd be like walking users through how to create a Google account so they can login to Oppia

**Comment by seanlip** [comment]
We do have not-very-technical users, and for those users it is helpful to
point them to a page saying "just follow these steps". Not all such users
live much of their lives in the digital realm or are comfortable
participating in technical forums -- they are worried they'll do something
wrong.

Also when we suggest to folks "file an issue", they might not realize that
this involves signing up, and be uncertain when directed to the sign up
screen about whether this is something they are actually supposed to do.

So I feel like having a page with clear self-sufficient step by step
instructions that we can point them to isn't a bad idea. If the
instructions within the flow on GitHub are clear, then we can just say
"after clicking X, follow the instructions presented until you reach this
screen" -- I agree we don't have to double-repeat them unless there's some
step in the flow people get stuck at. But knowing that they have to click
the new issue button (and where that button is), or knowing that it's fine
to go ahead and sign up, etc. -- these seem like things that are reasonable
to include in such a page, right?

**Comment by mkos11** [comment]
Based on the type of issues we're expecting from them, we could take advantage of the [issue forms feature in GitHub](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms).

**Comment by Ash-2k3** [comment]
I want to take this up if it's free to be taken.
