### ISSUE TITLE
Update linitng docs for run_lint_checks

### ISSUE THREAD

**Issue by HardikGoyal2003** [oppia/oppia-web-developer-docs#323]
[Discussion Reference](https://github.com/oppia/oppia/discussions/20319) for the issue.

[PR in which file was changed](https://github.com/oppia/oppia/pull/19760/files#diff-d7499d818f81d73250d1a5d674c09cbc530e235e8a2a3806b0229f1b1bc773b0)

This particular problem requires us to update all references of ``pre_commit_linter`` to ``run_lint_checks`` throughout the docs.

**Comment by HardikGoyal2003** [comment]
@Ash-2k3 Please assign me this issue.

**Comment by Ash-2k3** [comment]
Done, thanks!

**Comment by Ash-2k3** [comment]
Completed via https://github.com/oppia/oppia-web-developer-docs/pull/324
