### ISSUE TITLE
Fold "Common pull request workflows" into "Rules for making PRs"

### ISSUE THREAD

**Issue by U8NWXD** [oppia/oppia-web-developer-docs#336]
The wiki page https://github.com/oppia/oppia/wiki/Common-pull-request-workflows should be eliminated, and the bulk of its content should be moved to the soon-to-be-written "Rules for making PRs" page (currently at https://github.com/oppia/oppia/wiki/Make-a-pull-request). The parts of the "Common pull request workflows" page that are more like reference material for the dev workflow team should be moved to a new page in the dev workflow section of the wiki

**Comment by mirodoan** [comment]
### Contribution Proposal

Hi, I'm Miro. I'd like to contribute to this issue. Please review the checklist below, which I propose to update by integrating the content from "Common pull request workflows" into "Rules for making PRs." Let me know which items need improvement. Thank you! @U8NWXD 

### Essential Checklist

1. **Filename Change**: Rename the file from “Make-a-pull-request” to “Rules for making PRs”.

2. **Steps to Keep**: Retain the original content for Step 1, Step 2, Step 3, Step 5, Step 6, and Step 7.

3. **Modifications**: Update some of the original content in the “Make a pull request” file and incorporate information from "Common Pull Request Workflows", specifically:
   - **Step 4**: Pull Request Lifecycle, Draft Pull Requests, Labeling Pull Requests
   - **Step 8**: Working on Multiple Pull Requests

**For more details, please refer [here](https://docs.google.com/spreadsheets/d/1i4EbDiXLgm4z29T6CP__5NhFoL_6__HkxwctWfhljbQ/edit?gid=0#gid=0).**

**Comment by seanlip** [comment]
Hi @miro789, I think this seems reasonable -- thanks for outlining your changes so clearly and for helping out! I'm assigning you to this issue, feel free to make a PR and we can discuss more during the review phase if needed (but the general flavour of the changes proposed seems good). Thanks!

**Comment by mirodoan** [comment]
Hi @seanlip,

Thank you for taking the time to review my contribution. This is my first time submitting a PR to an open-source project, so I appreciate your guidance. I have created the PR [here](https://github.com/oppia/oppia-web-developer-docs/pull/393). Please take a look and provide any feedback or suggestions for improvement.

Thanks!

**Comment by U8NWXD** [comment]
This approach LGTM
