### ISSUE TITLE
Create Tutorial - Learn how to debug server errors which can't be easily reproduced locally

### ISSUE THREAD

**Issue by U8NWXD** [oppia/oppia-web-developer-docs#361]
## Skills covered

Codebase Navigation,
Figure out what code to change,
Debugging, Figure out reproduction steps from server error logs, Manual testing of the solution.

## Similar issues

[20031](https://github.com/oppia/oppia/issues/20031),
[19960](https://github.com/oppia/oppia/issues/19960)
[19696](https://github.com/oppia/oppia/issues/19696)

## Existing relevant pages

[oppia/wiki/Server-errors-and-solutions](https://github.com/oppia/oppia/wiki/Server-errors-and-solutions)

## Example

Run a git patch file to reproduce any of the bugs we faced in the past.

Potential options: https://github.com/oppia/oppia/issues/19387

**Comment by Ash-2k3** [comment]
Link to tutorial (Google Doc)- https://docs.google.com/document/d/1NJfEy0oeMMW20psCdrV9ScB9DHmk4UBE3BdcHOa4dCs/edit
