### ISSUE TITLE
Renaming the file paths to avoid issues on Windows

### ISSUE THREAD

**Issue by mirodoan** [oppia/oppia-web-developer-docs#396]
## Since Windows does not allow colons in file names, I think we need to rename these files in Git to remove or replace the colons.

Initially, I intended to fix it and create a Pull Request. However, these files cannot be displayed on my local Windows OS. 
@Ash-2k3 Could you please take a look and help me resolve these issues? Thanks a lot!
(/cc @U8NWXD for information)

### Specifically, the following files:

1. **Tutorial:-Learn-How-to-Write-and-Test-a-Non-Trivial-Beam-Job.md** 
2. **Tutorial:-Learn-to-figure-out-the-reproduction-steps-for-server-error.md** 

![error_window](https://github.com/user-attachments/assets/166c0284-bee2-48c5-ac4c-08e283319acf)

### Suggestions:
1. Rename the files using the `git mv` command:
   - ```bash
     git mv "Tutorial:-Learn-How-to-Write-and-Test-a-Non-Trivial-Beam-Job.md" "Tutorial-Learn-How-to-Write-and-Test-a-Non-Trivial-Beam-Job.md" 
     ```
   - ```bash
     git mv "Tutorial:-Learn-to-figure-out-the-reproduction-steps-for-server-error.md" "Tutorial-Learn-to-figure-out-the-reproduction-steps-for-server-error.md" 
     ```

2. Update the content in the `_Sidebar.md` file without colon:
   - `[[Tutorial - Learn-to-figure-out-the-reproduction-steps-for-server-error|Tutorial-Learn-to-figure-out-the-reproduction-steps-for-server-error]]`
   - `[[Tutorial - Learn to write and test a non-trivial beam job|Tutorial-Learn-How-to-Write-and-Test-a-Non-Trivial-Beam-Job]]`

**Comment by Ash-2k3** [comment]
Hi @miro789, thanks for reporting this issue. I will open a PR for this by today.
