### ISSUE TITLE
Explain the difference between E2E and Acceptance tests

### ISSUE THREAD

**Issue by oesgalha** [oppia/oppia-web-developer-docs#404]
The wiki has 2 very complete pages about E2E and Acceptance tests:

- https://github.com/oppia/oppia/wiki/Acceptance-Tests
- https://github.com/oppia/oppia/wiki/End-to-End-Tests

But reading those pages and inspecting the current test suites, the difference between an E2E and an Acceptance test isn't clear.
One of them uses Puppeteer and the other uses WebdriverIO.

Searching in the project discussions I've found this:
https://github.com/oppia/oppia/discussions/20064#discussioncomment-8926057

> we are currently migrating from e2e tests to acceptance tests so you don't need the e2e ones

Is this the case? If it is then maybe the E2E tests page can be updated to explain that those tests are deprecated in favor of the acceptance tests.

**Comment by seanlip** [comment]
Thanks for bringing this up, @oesgalha! You raise a great point. 

I've made a PR to fix it at https://github.com/oppia/oppia-web-developer-docs/pull/413, PTAL if you get a chance, and let me know if it's clear enough -- happy to get suggestions for improvement!

**Comment by oesgalha** [comment]
Hey @seanlip , I've read your PR and it looks great. The difference is clear now.

Thanks!
