### ISSUE TITLE
"Instructions for making PR passes" page is outdated

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-web-developer-docs#45]
I noticed this page and it seems obsolete: https://github.com/oppia/oppia/wiki/Instructions-for-making-PR-passes

Should we delete it from the wiki and the sidebar? Or should we edit it to reflect what @U8NWXD is currently doing as part of the weekly audit (so that others can help out in the future as well)?

**Comment by U8NWXD** [comment]
Yep, I agree we should update this page. Triaged and assigned to dev workflow

**Comment by seanlip** [comment]
This page was updated in mid-Aug 2023. I think the content on it might still be useful, I'll bring it up with the welfare team at a future meeting. Closing this issue for now.
