### ISSUE TITLE
Adding a backend library

### ISSUE THREAD

**Issue by chris7716** [oppia/oppia-web-developer-docs#50]
As it is mentioned [here](https://github.com/oppia/oppia/wiki/Third-party-libraries#add-a-backend-production-library-from-pip) in order to generate `requirements.txt` from `requirements.in` we should run `scripts/regenerate_requirements.py`. But in the [repository](https://github.com/oppia/oppia) I can not find `regenerate_requirements.py`.

How should this be done?

**Comment by seanlip** [comment]
For reference, it looks like this file was deleted recently as a result of this PR: https://github.com/oppia/oppia/pull/15602 .

(See its history [here](https://github.com/oppia/oppia/commits/develop/scripts/regenerate_requirements.py).)

@U8NWXD Could you please update the wiki pages? Thanks!

**Comment by gp201** [comment]
@heyimShivam would you be able to work on this issue?

**Comment by heyimShivam** [comment]
@gp201 i wouldn't able to help you in this issue, can you please assign this issue to someone who have understanding about python libraries
