### ISSUE TITLE
Update prerequisite installation instructions

### ISSUE THREAD

**Issue by gp201** [oppia/oppia-web-developer-docs#54]
As per this discussion (https://github.com/oppia/oppia/discussions/16507), some of the installation commands are not working.

Please take a look, test and update the instructions accordingly.

Current instructions:
https://github.com/oppia/oppia-web-developer-docs/blob/c0d21435b6dd117ccfc4fd31254cf1a3d9cb4c54/Installing-Oppia-(Linux%3B-Python-3).md?plain=1#L20-L31

**Comment by suyashmadhesia** [comment]
can I work on this issue? @U8NWXD

**Comment by U8NWXD** [comment]
@suyashmadhesia first of all, note that this is not a good first issue, so if you're looking for that, please follow the instructions in our wiki. If you still want to tackle this issue, you'll need a Linux machine where you can test the installation instructions.

**Comment by SD-13** [comment]
Hey @gp201 , Can I take this one?

**Comment by suyashmadhesia** [comment]
> @suyashmadhesia first of all, note that this is not a good first issue, so if you're looking for that, please follow the instructions in our wiki. If you still want to tackle this issue, you'll need a Linux machine where you can test the installation instructions.

Hey I have linux machine and I also have some good experience with linux so can you assign this issue to me ?

**Comment by SD-13** [comment]
@suyashmadhesia done!

**Comment by U8NWXD** [comment]
@suyashmadhesia thanks for taking up this issue! To help me plan, when do you intend to complete it?

**Comment by suyashmadhesia** [comment]
> @suyashmadhesia thanks for taking up this issue! To help me plan, when do you intend to complete it?

I will send PR in 1 or in maximum 2 days
