### ISSUE TITLE
Add Table of contents for the troubleshooting page.

### ISSUE THREAD

**Issue by gp201** [oppia/oppia-web-developer-docs#55]
Currently the [troubleshooting page](https://github.com/oppia/oppia-web-developer-docs/blob/develop/Troubleshooting.md) does not have a table do contents making hard for users to navigate the page.

**Comment by deadex-ng** [comment]
@U8NWXD can I work on this issue?

**Comment by gp201** [comment]
@deadex-ng have you signed the CLA form and the contributor survey (https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#setting-things-up)?

**Comment by deadex-ng** [comment]
@gp201 Yes, I've done that.

**Comment by gp201** [comment]
@deadex-ng I have assigned you to this issue. You can go ahead and open a PR when you're ready

**Comment by deadex-ng** [comment]
I've made a [PR](https://github.com/oppia/oppia-web-developer-docs/pull/75)
