### ISSUE TITLE
Update the "Writing state migrations" page

### ISSUE THREAD

**Issue by vojtechjelinek** [oppia/oppia-web-developer-docs#57]
The https://github.com/oppia/oppia/wiki/Writing-state-migrations needs to be updated with more recent information. Basically verify if all instructions still apply or not.

**Comment by U8NWXD** [comment]
Thanks for raising this @vojtechjelinek. What team is in charge of the state migrations? I think they'd be the best for updating the instructions. AFAIK no one on dev workflow is familiar with them

**Comment by vojtechjelinek** [comment]
I'm not sure, I think in many cases LaCE needs to write schema migrations and also a data and stability people need sometimes to write schema migrations.

**Comment by U8NWXD** [comment]
OK, maybe a better question is who knows how to write schema migrations (i.e. who is qualified to update the page)?

**Comment by vojtechjelinek** [comment]
A few people, but two GSoC contributors were writing them in their projects so they might be able to help. @lkbhitesh07 @Manan-Rathi

**Comment by U8NWXD** [comment]
@lkbhitesh07 @Manan-Rathi are either of you interested in updating this wiki page?

**Comment by lkbhitesh07** [comment]
> @lkbhitesh07 @Manan-Rathi are either of you interested in updating this wiki page?

Hey @U8NWXD, Sorry for the delayed response. I will not be active till 10th December if that is fine then I will be able to help after that.
Thanks

**Comment by U8NWXD** [comment]
@lkbhitesh07 are you able to update this wiki page now?

**Comment by lkbhitesh07** [comment]
> @lkbhitesh07 are you able to update this wiki page now?

Sure, I will update the page via PR and will let you know.
Thanks

**Comment by U8NWXD** [comment]
Thanks @lkbhitesh07! When do you plan to finish updating the wiki page?

**Comment by lkbhitesh07** [comment]
Hey @U8NWXD, I do not have right to push the changes to `oppia-web-developer-docs` repo. Could you please provide it?
cc/- @seanlip 
Thanks

**Comment by seanlip** [comment]
@lkbhitesh07 You should do the usual thing of making a fork and pushing to that fork and opening a PR. You don't need any special permissions for that.

**Comment by lkbhitesh07** [comment]
> @lkbhitesh07 You should do the usual thing of making a fork and pushing to that fork and opening a PR. You don't need any special permissions for that.

Cloned via ssh, now it seems to work. It was giving authentication error previously. Opened up the PR - https://github.com/oppia/oppia-web-developer-docs/pull/72
Thanks
