### ISSUE TITLE
Update "Launching new features" wiki page

### ISSUE THREAD

**Issue by kevintab95** [oppia/oppia-web-developer-docs#59]
Update "Launching new features" wiki page with instructions on how to conduct feature reviews.

Perhaps use information from these slides: https://docs.google.com/presentation/d/1PyM9fLW_RTptgvbmR0wc6n87LaitXlSHOyxd__iz8Bg/edit

**Comment by akarshansonkar** [comment]
hello @seanlip would you please assign this issue to me ? i would surely give my best to resolve this ....

**Comment by seanlip** [comment]
@akarshansonkar Per the guidance at https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue, please provide an explanation of what your PR will do (with details on what pages you're changing, what you plan to change in each page, etc.). If it looks good, we can assign you to this issue.

Please also follow the other instructions on that wiki page if you have not yet done so. Thanks!

**Comment by vedant-z** [comment]
@seanlip I would love to try this issue and explain how would I solve this issue, but the slide link you provided is'nt accessible. It says you need to request access.

**Comment by seanlip** [comment]
Sorry about that, @vedant-z. It's accessible now.
