### ISSUE TITLE
Add link to coverage report discussion to backend test debugging page

### ISSUE THREAD

**Issue by U8NWXD** [oppia/oppia-web-developer-docs#61]
Add link to https://github.com/oppia/oppia/wiki/Backend-tests#coverage-reports to https://github.com/oppia/oppia/wiki/Debug-backend-tests

**Comment by U8NWXD** [comment]
@Nik-09 would you be able to work on this issue?

**Comment by Nik-09** [comment]
Hi @U8NWXD yes I will be able to take this issue.

Thank you.

**Comment by U8NWXD** [comment]
Solved by https://github.com/oppia/oppia-web-developer-docs/pull/70
