### ISSUE TITLE
Add troubleshooting for timeout error

### ISSUE THREAD

**Issue by aks681** [oppia/oppia-web-developer-docs#69]
When installing Oppia for the first time, githubusercontent requests may timeout due to DNS issues. Add points to address this (more context [here](https://github.com/oppia/oppia/discussions/16698)).

**Comment by U8NWXD** [comment]
@aks681 what's going on here? I don't understand how a DNS issue would lead to a timeout when downloading from githubusercontent for only one path but not others

**Comment by aks681** [comment]
Yeah, I am also not sure how it happened, but what I observed was that even loading images in PRs (which uses the same domain name) wasn't working at this point, but changing DNS provider to 1.1.1.1 fixed it. Might have been a one-off issue, not sure.

**Comment by U8NWXD** [comment]
This sounds like an issue with the user's DNS configuration, which seems too generic for our troubleshooting guide, so I'm closing this. Please reopen if you disagree!
