### ISSUE TITLE
Remove question mark in file name

### ISSUE THREAD

**Issue by deadex-ng** [oppia/oppia-web-developer-docs#73]
Remove the question mark in the [file](https://github.com/oppia/oppia-web-developer-docs/blob/develop/Issues-with-installation%3F.md) name.
The file causes issues when merging because in windows a file name cannot contain any of the following characters:` \ / : * ? " < > |"`

For reference: [check here](https://developercommunity.visualstudio.com/t/git-checkout-fails-with-invalid-error-message/1473599#T-N1491297)

**Comment by U8NWXD** [comment]
Hmm I hadn't thought of this. We don't do any development on Windows (it's a pain to get the dev tools set up), so instead we run Linux on Windows.

@gp201 do you think it's worth supporting documentation-writing on Windows even though we don't support code development there?

EDIT: Also, is it true that on Windows under WSL we can have files with question marks? I'm assuming that's the case, but I'm not sure

**Comment by deadex-ng** [comment]
It is true that on Windows under WSL we can have files with question marks.

**Comment by gp201** [comment]
> @gp201 do you think it's worth supporting documentation-writing on Windows even though we don't support code development there?

@U8NWXD I don't think we have to support development via windows since all of the contributors use WSL for windows. However, I think it will be good practice to avoid special characters in file names.

**Comment by U8NWXD** [comment]
Opened https://github.com/oppia/oppia-web-developer-docs/pull/78 to fix this
