### ISSUE TITLE
[wiki documentation updation] pyenv installation problem in Installing Oppia (Linux; Python 3)

### ISSUE THREAD

**Issue by ThakurSaAbhay** [oppia/oppia-web-developer-docs#83]
[Installing Oppia (Linux; Python 3)](https://github.com/oppia/oppia/wiki/Installing-Oppia-%28Linux%3B-Python-3%29#:~:text=If%20you%20see%20the%20warning%20at%20the%20end%2C%20add%20the%20following%20lines%20to%20your) 

The second step is not up to date [curl pyenv.run | bash] and isn't working in windows ubuntu.
Which is creating a problem for new users and they are loosing their confidence because of it.

![Screenshot (91)](https://user-images.githubusercontent.com/98638332/212146290-d42fb774-cfb4-4cd3-a343-d26556b479c1.png)

I can resolve this issue by giving the new way to install pyenv in the bash.

**Comment by seanlip** [comment]
Moving this to the wiki repo at https://github.com/oppia/oppia-web-developer-docs instead.

/cc @U8NWXD @gp201 FYI

**Comment by U8NWXD** [comment]
@ThakurSaAbhay what's out of date about the second step? https://pyenv.run/ points to the correct bash code for me:

```bash
#!/bin/bash
#
# Usage: curl https://pyenv.run | bash
#
# For more info, visit: https://github.com/pyenv/pyenv-installer
#
index_main() {
    set -e
    curl -s -S -L https://raw.githubusercontent.com/pyenv/pyenv-installer/master/bin/pyenv-installer | bash
}

index_main
```

**Comment by ThakurSaAbhay** [comment]
Don't know it wasn't working I had to clone the actual repository to install I tried it many times

**Comment by U8NWXD** [comment]
What errors were you getting?

**Comment by ThakurSaAbhay** [comment]
It's sorted now I've seen many people were getting the same problem on discussion So I thought it was an issue but it's because of DNS it's not able to connect and fetch the repository that's why everybody are getting problems. I'm closing this issue it's totally fine.
