### ISSUE TITLE
How to Safely Add Dependencies

### ISSUE THREAD

**Issue by U8NWXD** [oppia/oppia-web-developer-docs#85]
We should decide on and document a policy for adding dependencies. Here is a starting policy for discussion:

-----

All dependencies we add to our projects introduce risks. These include security risks (an attacker could inject malicious code into Oppia if they control one of our dependencies) and maintainability risks (if a dependency isn't well-maintained, their bugs could break Oppia). To mitigate these risks, we should do the following:

1. **Minimize** the number of dependencies we have and the extent to which we rely on them. Especially for small dependencies, it may be better to implement them ourselves. That said, for security-related operations (especially cryptographic ones), relying on a trusted library may be better than rolling our own and possibly making mistakes.
2. **Vet** any dependencies we do have. This means checking that the we trust the maintainer to not add malicious code, maintain security measures to stop someone else from adding malicious code, and to maintain the dependency by fixing bugs. For small dependencies, this may mean reviewing their code manually. For larger ones, we may have to rely on reputation.
3. **Pin** dependencies to a specific, immutable version. Here are some examples for types of dependencies we use often:
   * PyPI: Use `==` to specify a particular version number, e.g. `my_dependency==1.0.5`. Do *not* use `=>`, which will tell `pip` to automatically install the latest version of a package without our involvement.
   * NPM: Use `yarn.lock` to pin dependency versions (this happens automatically for all NPM dependencies handled by yarn).
   * GitHub Actions: Use a commit hash ("SHA value" in the [docs](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-release-management-for-your-custom-actions)) when specifying a third-party dependency. For example: `- uses: actions/javascript-action@172239021f7ba04fe7327647b213799853a9eb89`.
4. **Hash** dependencies using a hashing algorithm [approved by NIST](https://csrc.nist.gov/projects/hash-functions) and compare that hash to a list of the values we expect. In most cases, we should take advantage of package managers' built-in functionality to verify checksums. This ensures that even if someone manages to change the code of a supposedly immutable dependency version (for example, there are ways to do this in PyPI where packages can be provided either as source code or as binaries), we won't install the malicious dependency.
5. **Upgrade** dependencies every month to ensure we benefit from any security fixes.

Ideally we'd also constrain dependencies to limit the damage they can do, but that isn't really supported by any of the dependency ecosystems we use yet

**Comment by U8NWXD** [comment]
@seanlip @gp201 what do you think?

**Comment by seanlip** [comment]
LGTM. Thanks! Maybe for the "pinning step" we should be more directive -- e.g. "for GitHub Actions dependencies, do this; for Python dependencies, do this; etc."? Since sometimes the details matter, e.g. pinning to release version (not sure if that can change under us) or pinning to commit hash (probably more immutable).

Not sure though. Might be too much detail, but feels like it's potentially worth documenting.

For point 4 do we want to specify a list of allowed hashing algorithms (or again do a breakdown by frontend/backend/Actions)?

For point 5, how regularly is regularly?

But overall, this looks really great. Thanks!

**Comment by U8NWXD** [comment]
All but point 5 is updated. For the hash algorithm I deferred to NIST

**Comment by seanlip** [comment]
Thanks! LGTM.

**Comment by U8NWXD** [comment]
Updated point 5 after checking with @vojtechjelinek

**Comment by seanlip** [comment]
LGTM, thanks.

@U8NWXD just to check, should this issue be assigned to you?
