### ISSUE TITLE
Add .gitignore file to wiki repo

### ISSUE THREAD

**Issue by seanlip** [oppia/oppia-web-developer-docs#92]
I was reviewing https://github.com/oppia/oppia-web-developer-docs/pull/80/files and it looks like a .DS_Store file was mistakenly included with the PR.

Should we add a .gitignore to this repo so that such files are ignored, just like we do in the [Web repo](https://github.com/oppia/oppia/blob/develop/.gitignore)?

**Comment by seanlip** [comment]
@U8NWXD please could you advise on whether this is a good idea -- not sure if it would result in any issues with the sync or if there's any problems adding .gitignore files in wiki repos. I think it should be fine but wanted to double-check. Thanks!

**Comment by Flamki** [comment]
i want to work on this issues please assign me

**Comment by U8NWXD** [comment]
I agree--it should be fine

**Comment by AnmolSirola** [comment]
@U8NWXD @seanlip Can I work on this issue ?

**Comment by U8NWXD** [comment]
@AnmolSirola if you want to work on this issue, please follow our [instructions for taking up a good first issue](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue). Specifically, make sure your comment "describes in more detail how you'd tackle the issue (e.g. explain which file(s) you would modify and what changes you would make). If your explanation makes sense, we'll assign the issue to you."

**Comment by vedant-z** [comment]
@U8NWXD I would like to work on this issue. 

To tackle this one I would basically create a .gitignore file and add names of files which we don't want to include in unnecessary conditions. 

For example: I will include possible file ".DS_Store" and other files.

I would need some help on which files specifically need to be ignored.

Thanks

**Comment by AnmolSirola** [comment]
@U8NWXD In order the solve this issue,
I will make a .gitignore file (that will tell Github which files to ignore when committing our project).     I will add ".DS_Store" files in that .gitignore file.

I would like you to help him on which files should I specifically add on .gitignore files.

Thank you

**Comment by seanlip** [comment]
The first person to follow the instructions was @vedant-z so I'm assigning this issue to them.

Re the question, just ".DS_Store" should suffice for now. You could maybe include some of the other stuff from [here](https://github.com/oppia/oppia/blob/develop/.gitignore) but please omit anything that's not relevant and that would never get into this repo during local development (such as third_party/ or python stuff). Thanks!

@AnmolSirola Please feel free to pick a different issue.

**Comment by AnmolSirola** [comment]
But I asked for this issue first , I was just waiting for  your reply :/

**Comment by seanlip** [comment]
@AnmolSirola As @U8NWXD said, please follow [these instructions](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue) when you want to ask for a good first issue.

For background, we don't assign issues just because folks ask for them -- anyone can ask for an issue. Instead, we assign them to the first person we think can actually do them, because otherwise we find that people "squat" on issues and they don't get solved, while remaining blocked for other contributors. So, in the future, please read that wiki page fully and follow the guidelines so that things operate smoothly.

**Comment by AnmolSirola** [comment]
@U8NWXD @seanlip Thanks for guiding, will keep it in mind.

**Comment by Harsh-0077** [comment]
is there anyone working on this issue or may i start on it

**Comment by vedant-z** [comment]
@Harsh-0077 Firstly this issue has been resolved and secondly as stated by @seanlip: 

As @U8NWXD said, please follow [these instructions](https://github.com/oppia/oppia/wiki/Contributing-code-to-Oppia#choosing-a-good-first-issue) when you want to ask for a good first issue.

For background, we don't assign issues just because folks ask for them -- anyone can ask for an issue. Instead, we assign them to the first person we think can actually do them, because otherwise we find that people "squat" on issues and they don't get solved, while remaining blocked for other contributors. So, in the future, please read that wiki page fully and follow the guidelines so that things operate smoothly.

**Comment by seanlip** [comment]
Hm, in addition to what @vedant-z said, this was actually fixed in #101 but I'm not sure why merging that PR didn't close this issue. Closing it!
