### ISSUE TITLE
Include Mypy in CI checks

### ISSUE THREAD

**Issue by SD-13** [oppia/oppia-web-developer-docs#97]
Add Mypy in the CI to check for type annotations in the wiki repo.

Suggested [here](https://github.com/oppia/oppia-web-developer-docs/pull/84/#discussion_r1083556925) by @U8NWXD

**Comment by U8NWXD** [comment]
We should enforce mypy strictly (i.e. require that everything be typed and that there are no type errors). Checks should be easy to run locally, be run on each commit to develop, and be enforced for all PRs to develop

**Comment by deadex-ng** [comment]
@gp201 I would like to work on this

**Comment by gp201** [comment]
@deadex-ng I have assigned this issue to you.

**Comment by deadex-ng** [comment]
@gp201 Should the mypy workflow check all python files or it should only check python files that have been changed when a PR is made?

**Comment by U8NWXD** [comment]
We need to check all Python files because a change in one file could cause a type error in another (unmodified) file

**Comment by Shivkant-Chauhan** [comment]
@deadex-ng please update the project board with the expected merge date.

**Comment by deadex-ng** [comment]
@Shivkant-Chauhan I made a [PR](https://github.com/oppia/oppia-web-developer-docs/pull/119) and it was merged.

**Comment by Shivkant-Chauhan** [comment]
Closing this as completed by #119
